AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 240
    MemorySize: 512
  Api:
    BinaryMediaTypes:
      - image~1png

Resources:
  MnistFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Mnist:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mnist
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./mnist-function
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MnistApi:
    Description: "API Gateway endpoint URL for Prod stage for Mnist function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mnist/"
  MnistFunction:
    Description: "Mnist Lambda Function ARN"
    Value: !GetAtt MnistFunction.Arn
  MnistFunctionIamRole:
    Description: "Implicit IAM Role created for Mnist function"
    Value: !GetAtt MnistFunctionRole.Arn
